
import BreadcrumbComp from "../../layout/shared/breadcrumb/BreadcrumbComp";
import React from "react";
import CheckBoxTable from '@/app/components/tables/checkbox/index'
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "CheckBox Table",
  description: "Generated by create next app",
};
const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Checkbox Table",
  },
];

const CheckboxTable = () => {

  return (
    <>
      <BreadcrumbComp title="Checkbox Table" items={BCrumb} />
      <CheckBoxTable/>
    </>
  );
};

export default CheckboxTable;
