import React from "react";
import BreadcrumbComp from "../../layout/shared/breadcrumb/BreadcrumbComp";
import ApexGradientChart from "@/app/components/charts/ApexGradientChart";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Gradient Chart",
  description: "Generated by create next app",
};
const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Gradient",
  },
];
const GradientChart = () => {
  return (
    <>
      <BreadcrumbComp title="Chart Apex Gradient" items={BCrumb} />
      <ApexGradientChart />
    </>
  );
};

export default GradientChart;
