

import BreadcrumbComp from "../../layout/shared/breadcrumb/BreadcrumbComp";
import React from "react";
import HoverTable from '@/app/components/tables/hover/index'
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Hover Table",
  description: "Generated by create next app",
};
const BCrumb = [
    {
      to: "/",
      title: "Home",
    },
    {
      title: "Hover Table",
    },
  ];

const hoverTable = () => {
 
  return (
    <>
      <BreadcrumbComp title="Hover Table" items={BCrumb} />
      <HoverTable/> 
    </>
  );
};

export default hoverTable;
