
import React from "react";
import BreadcrumbComp from "../../layout/shared/breadcrumb/BreadcrumbComp";
import ApexColumnChart from "@/app/components/charts/ApexColumnChart";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Column Chart",
  description: "Generated by create next app",
};
const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Column",
  },
];
const ColumnChart = () => {

  return (
    <>
      <BreadcrumbComp title="Chart Apex Column" items={BCrumb} />
      <ApexColumnChart/>
    </>
  );
};

export default ColumnChart;
